### ISSUE TITLE
G915 Keyboard Logitech

### ISSUE THREAD

**Issue by CaioZero** [Aurora-RGB/Aurora#145]
### Expected Behaviour
Should be possibly to change media keys colors previous, pause/play,next, mute, m1,m2,m3,mr,lightspeed, bluetooth, game mode, bright

### Actual Behaviour
Non of those keys related above are working as should be (being colorized, etc)

### Reproduction steps
Just try to set any color to keys that were quoted above

### Frequency
Everytime

### Aurora Version:
V131

### Previously an Issue?
Yes

**Comment by joaocaparroz** [comment]
I think the only keys we should be able to change colors are: brightness, previous, play/pause, next and mute.
I can confirm those keys don't change colors, even with solid fill layer, and I can change them via G Hub.

**Comment by Aytackydln** [comment]
Hi, being able to change them on Ghub doesn't mean we can change them with sdk (logitech and it' rgb.net implementation). If you use rgb.net, if the keys are visible and testing them works then it is a mapping issue in Aurora.

If they still don't work they can be only controlled via OpenRGB because OpenRGB mimics Ghub protocol
